sudo: false
language: scala

matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.12.4
  - jdk: oraclejdk8
    scala: 2.11.12
  - jdk: oraclejdk9
    scala: 2.12.4

script:
- sbt ++$TRAVIS_SCALA_VERSION test